export enum MutationsTypes {
    SET_POSTS = 'SET_POSTS',
    SET_AUTHORS = 'SET_AUTHORS',
    SORT_BY_DECRESCENT = 'SORT_BY_DECRESCENT',
    SORT_BY_CRESCENT = 'SORT_BY_CRESCENT',
    SET_FILTERS = 'SET_FILTERS',
    SET_LOADING = 'SET_LOADING',
}